
Blog.create! :status => "published", :published_at => "2009-07-09 13:54:01", :permalink => "test", :title => "évaluation", :excerpt => "l’entretien d’évolution", :text => "publié dans FocusRH."


Blog.create! :status => "published", :permalink => "donner-de-la-valeur-aux-entretiens-devaluation", :title => "Donner de la valeur aux entretiens d''évaluation", :excerpt => "Par exemple, l’entretien d’évolution est idéal pour la mobilité. Mais les données sont difficiles à exploiter sans outil informatisé", :text => '« <em>Par exemple, l’entretien d’évolution est idéal pour la mobilité. Mais les données sont difficiles à exploiter sans outil informatisé</em>. » Francis Bergeron, DRH chez SGS.\r\n\r\n« <em class="spip">La mobilité mérite d’être processée</em>. » Nicole Prud''homme, Directrice du département Talent Management du cabinet Hudson.\r\n\r\nRetrouvez tout l''article "<a href="http://www.focusrh.com/article.php3?id_article=3763">Les DRH misent sur la mobilité interne</a>", publié dans FocusRH.',


INSERT INTO `blogs` (`created_at`, `permalink`, `title`, `excerpt`, `text`) VALUES('2009-07-09 13:54:01',
'donner-de-la-valeur-aux-entretiens-devaluation', 'Donner de la valeur aux entretiens d''évaluation', '',
'« <em>Par exemple, l’entretien d’évolution est idéal pour la mobilité. Mais les données sont difficiles à exploiter sans outil informatisé</em>. » Francis Bergeron, DRH chez SGS.\r\n\r\n« <em class="spip">La mobilité mérite d’être processée</em>. » Nicole Prud''homme, Directrice du département Talent Management du cabinet Hudson.\r\n\r\nRetrouvez tout l''article "<a href="http://www.focusrh.com/article.php3?id_article=3763">Les DRH misent sur la mobilité interne</a>", publié dans FocusRH.');

INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-07-04 19:01:19', 'mobilite-et-recrutement', 'Mobilité et recrutement !', '', 'Qameha teste avant ses clients son produit, un peu, et les réalités des\r\nPMEs, beaucoup :\r\n\r\n- nous déménageons !\r\nMerci à l''incubateur Télécom ParisTech Entrepreneurs de nous faire confiance et nous\r\naccueillir. On ne va pas très loin tout seul, et l''incubateur nous\r\npermet de partager un espace, des idées, des solutions, des cv, parce\r\nque ...\r\n\r\n- nous recrutons : et recherchons des geeks ruby on rails à partir de la\r\nrentrée.\r\n\r\n- Qameha met la GPEC (gestion prévisionnelle de l''emploi et des\r\ncompétences) à la portée des PMEs, et la teste !\r\nCedric m''a appris à brancher mon ordinateur, Alexis se remet à l''anglais\r\nen prévision de notre croissance exponentielle, et nous savons\r\nmaintenant tous faire fonctionner la machine à café.');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-07-09 13:54:01', 'donner-de-la-valeur-aux-entretiens-devaluation', 'Donner de la valeur aux entretiens d''évaluation', '', '« <em>Par exemple, l’entretien d’évolution est idéal pour la mobilité. Mais les données sont difficiles à exploiter sans outil informatisé</em>. » Francis Bergeron, DRH chez SGS.\r\n\r\n« <em class="spip">La mobilité mérite d’être processée</em>. » Nicole Prud''homme, Directrice du département Talent Management du cabinet Hudson.\r\n\r\nRetrouvez tout l''article "<a href="http://www.focusrh.com/article.php3?id_article=3763">Les DRH misent sur la mobilité interne</a>", publié dans FocusRH.');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-07-09 16:45:20', 'mobilite-pour-quoi-faire', 'Mobilité, pour quoi faire ?', '', '');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-09-02 08:04:38', 'qameha-recrute-2-developpeurs-ruby-on-rails', 'Qameha recrute 2 développeurs Ruby on Rails', '', 'Paris, le 2 septembre 2009\r\n\r\nQameha développe une application B2B en mode Saas dans le domaine des ressources humaines. Cette application est composée de plusieurs modules et le premier a déjà été adopté en béta test par des clients partenaires. Depuis début juillet, Qameha est hébergé au sein de l''incubateur de Télécom Paris Tech.\r\n\r\nNous recherchons deux développeurs Ruby on Rails junior ou expérimenté(e)  .\r\n\r\nCDI\r\nRémunération selon expérience.\r\n\r\nPoste :\r\nAu sein d''une équipe de trois associés fondateurs, vous êtes complètement associé(e) au développement de l''entreprise.\r\nVous reportez à l''associé en charge des IT (<a href="http://twitter.com/alexip">@alexip</a>) et prenez en charge le développement de modules fonctionnels, de l''écriture du code aux tests.\r\nLe développement est Agile. Nous mettrons en oeuvre des méthodes de développement <strong>Scrum et TDD</strong>.\r\n\r\nVous évoluez au rythme de la société soit en management (croissance de l''équipe IT), soit vers des axes de recherches (partenariats laboratoires), soit de web marketing.\r\n\r\nEnvironnement technique\r\n- Ruby on Rails\r\n- Cucumber, Webrat\r\n- git, capistrano\r\n- mod_rails, ubuntu\r\n- mysql\r\n\r\nQualité du code / maintenance serveur / design d''interface seront 3 axes supplémentaires discriminant.\r\n\r\n<strong>Anglais excellent impératif\r\n</strong>Lieu : Paris\r\n\r\nSi vous êtes intéressé(e), contactez nous à <a href="mailto:qameha@qameha.com">qameha@qameha.com</a> en joignant votre cv,\r\n\r\nSinon n''hésitez pas à diffuser cette annonce.');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-10-08 10:42:12', 'laureat-du-concours-creacc-2009-cest-parti-pour-le-11eme-tremplin-entreprises', 'Lauréat du concours Cré''Acc 2009, c''est parti pour le 11ème Tremplin Entreprises', '', 'Après avoir été Lauréat du concours Cré''Acc 2009 organisé par l''Ordre des Experts Comptables et la Chambre de Commerce et d''Industrie de Paris, Qameha va maintenant participer au 11ème Tremplin Entreprises (<a href="http://www.tremplinentreprises.com">www.tremplinentreprises.com</a>) coorganisé par le Sénat et l''ESSEC');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-10-08 11:10:39', 'colloque-national-%c2%ab-linnovation-pour-lemploi-%c2%bb-organise%cc%81-par-yvon-gattaz-le-8-octobre-2009', 'Colloque national « l''innovation pour l''emploi » organisé par Yvon Gattaz le 8 octobre 2009', '', 'QAMEHA, spécialiste de la Gestion de la Valeur Humaine dans l''entreprise, intervient lors de la table ronde du colloque national « l''innovation pour l''emploi des jeunes », organisé par l''association jeunesse et entreprise créée et présidée par Yvon Gattaz.\r\n\r\nQameha a développé une application web (SaaS) pour les PME et Entreprises de Taille Intermédiaires (ETI) souhaitant améliorer significativement la gestion des compétences et de la valeur humaine dans l''entreprise. Ce logiciel comprend une suite de trois modules    :    « recrutement »,    évaluation    des    collaborateurs »    et    mobilité    interne », destinés à acquérir des meilleurs éléments grâce à un processus de recrutement optimisé, motiver leurs collaborateurs et capitaliser sur les compétences internes grâce à un processus d''évaluations couplé un outil de mobilité interne\r\nGrâce à Qameha les PME et ETI améliorent leur compétitivité à améliorant leur capacité d''acquisition et de fidélisation des meilleurs collaborateurs.\r\nQameha limite à un groupe de clients partenaires l''utilisation de sa version beta jusqu''en décembre 2006.\r\nLe colloque national 2009 de l''AJE est ouvert par Monsieur Luc Chatel, Ministre de l''éducation national et clos par Madame Christine Lagarde, Ministre de l''économie et des Finances. Interviendront également, Messieurs Axel Kahn, Président de l''Université Paris- Descartes, Pascal    Morand, Directeur Général ESCP-Europe, Olivier Barberot, Directeur exécutif en charge des RH du groupe Orange, Jacques Servier, Président- Fondateur des Laboratoires Servier, Martin Hirsch, Haut Commissaire à la Jeunesse\r\nContacts Presse\r\nLéonard Briot de La Crochais Tel : 0173042773 leonard.briot@qameha.com');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-10-27 16:38:51', 'le-collaborateur-acteur-de-son-evolution-professionnelle', 'Le collaborateur, acteur de son évolution professionnelle', '', '"<em>Afin de rendre le collaborateur acteur de son évolution professionnelle, nous avons voulu que le logiciel de GPEC que nous avons déployé soit accessible non seulement au département RH et aux managers mais également aux collaborateurs. Ainsi le collaborateur a accès à ses propres informations (fonctions, entretien annuel...), le manager aux siennes et à celles de ses collaborateurs et ainsi de suite</em>." <span class="spip">Pierre-Marie Argouarc’h, DRH de la Française des Jeux.</span>\r\n\r\n<span class="spip">Retrouver tout l''article <span style="background-color: #ffffff;">"<strong> <a href="http://www.focusrh.com/article.php3?id_article=4048">La mise en place de la GPEC doit être rapide</a></strong>", publié dans FocusRH le 22/10/09.</span></span>');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-11-10 13:26:06', 'lentretien-devaluation-une-etape-cruciale-en-periode-de-crise', 'L''entretien d''évaluation : une étape cruciale en période de crise', '', 'L''entretien d’évaluation est bien souvent vécu comme un challenge - de surcroît en la période actuelle. Ce point d’étape est le moment idéal pour dresser un bilan sur le travail effectué, parler des satisfactions, des attentes – dans la mesure du raisonnable – et pour fixer les objectifs pour la nouvelle année.\r\n\r\nRetrouver tout l''article  <strong>"<a href="http://www.jobeticrh.net/L-entretien-d-evaluation-une-etape-cruciale-en-periode-de-crise_a256.html" target="_blank">L''entretien d''évaluation : une étape cruciale en période de crise</a>" publié sur Jobetic.Rh</strong>');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-11-10 13:32:21', 'conserver-ses-talents-en-periode-de-crise', 'Conserver ses talents en période de crise', '', 'Préserver vos collaborateurs talentueux est essentiel pour passer la crise et être prêt lors de la reprise économique.\r\n\r\nRetrouver l''ensemble de l''article "<a href="http://www.journaldunet.com/management/ressources-humaines/conseil/conserver-les-talents-dans-son-equipe/conserver-ses-talents-en-periode-de-crise.shtml" target="_blank">Conserver ses talents en période de crise</a>" publié sur Le Journal du Net');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-12-08 11:28:25', 'on-parle-de-nous', 'On parle de nous', '', '<h1>Un nouvel acteur du e-recrutement : Qameha</h1>\r\n<h2>Le recrutement est un vrai défi pour les entreprises. Il ne suffit plus aux sociétés d’être concurrentielles et attractives pour que les meilleurs profils les rejoignent. Qameha est une application internet de gestion des recrutements, de la mobilité interne et des évaluations conçue et réalisée par des opérationnels des Ressources Humaines. Son but ? Simplifier et structurer le processus et conduire les cadres à s’impliquer eux-mêmes dans le recrutement de leurs équipes.</h2>\r\n<h2>My RH Line a rencontré Léonard Briot de la Crochais, Directeur de la Stratégie et des Partenariats de Qameha.</h2>\r\nRetrouvez <a href="http://www.myrhline.fr/actualite-rh/un-nouvel-acteur-du-e-recrutement-qameha.html">l''article complet</a> publié sur myrhline.com le 8 décembre 2009');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2009-12-09 15:09:01', 'de-limportance-des-comptes-rendus-dentretien-devaluation', 'De l''importance des comptes rendus d''entretien d''évaluation', '', 'Avec la fin de l''année qui approche, les entretiens annuels d''évaluation s''organisent. Certains peuvent être tentés d''en faire un simple rendez-vous formel. Pourtant la jurisprudence vient encore de rappeler que cette entrevue ne doit pas être prise à la légère, ni par l''employeur ni par le salarié.\r\n\r\nRetrouver <a href="http://www.lentreprise.com/3/1/4/article.asp?ida=22027">l''article complet</a> publié le 7 décembre 2009 sur www.lentreprise.com');
INSERT INTO `wp_posts` (`post_date`, `post_name`, `post_title`, `post_excerpt`, `post_content`) VALUES('2010-01-06 12:10:16', 'recherchons-ruby-on-rails-jedi-master', 'Recherchons Ruby on Rails Jedi Master', '', 'Qameha Meha, Railers et Rubyists !\n\nNous cherchons un développeur Ruby + Rails de 4 - 5 ans d''experience :\n- qui soit ceinture noire en langages objets\n- qui ne puisse coder sans d''abord écrire les tests\n- qui vendrai son âme pour pouvoir pair programmer\n\nL''équipe IT est actuellement composée de 3 personnes et communique principalement en anglais.\n\nPoste basé à Paris, rémunération selon expérience, ...\nContact : ror.qameha@qameha.net\n@qameha / @alexip \n');


    t.string   "title"
    t.text     "text"
    t.integer  "user_id"
    t.datetime "published_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "status",       :default => "draft"
    t.text     "excerpt"
    t.string   "permalink"
