
blog = Blog.create! :status => "draft", :published_at => "2010-01-25 11:54:01",:permalink => "la-fidelite-du-ver-a-soie",:title => "La fidélité du ver à soie",:excerpt => "new post",:text => "new text"


blog.update_attributes :excerpt =>  "<p>Nous sommes bien placés pour le voir, l'activité de recrutement redémarre en France, avec un évident effet de ciseaux entre plusieurs plans de réductions d'effectifs à venir et une progression constante des postes ouverts.</p><p>Au-delà des effets classiques de retournement du marché de l'emploi (peu de postes mais candidats très réticents à se mettre en danger), la situation actuelle appelle deux réflexions :</p>"

blog.update_attributes :text => "<p><b>Nous sommes bien placés pour le voir, l'activité de recrutement redémarre en France, avec un évident effet de ciseaux entre plusieurs plans de réductions d'effectifs à venir et une progression constante des postes ouverts.</b></p>\
<p>Au-delà des effets classiques de retournement du marché de l'emploi (peu de postes mais candidats très réticents à se mettre en danger), la situation actuelle appelle deux réflexions :</p>\
<ol><li> Comme chaque période de tension (manque de visibilité, inquiétudes), la crise financière et ses répercussions économiques ont cristallisé les attitudes des employeurs et exprimé les valeurs réelles de ceux-ci. Là où tel cabinet d'audit et conseil serre les dents, explique, mais garde tout le monde à bord, tel autre dégraisse massivement.\
<br/>Là où un management de qualité reconstruit son projet d'entreprise en fonction de la situation, d'autres ne font que répercuter sans discernement, ni grand effet, la pression venue de leurs actionnaires.\
<br/>On se prend à espérer que les uns et les autres, employés, managers, employeurs, garderont mémoire de tout cela,\
</li>\
<li> Qui a raison ? Quel est la bonne pratique ?\
<br/>Du point de vue moral, affronter la tempête en sauvant l'équipage est sans doute la seule attitude estimable. C'est d'ailleurs globalement celle des groupes à capitaux familiaux.\
<br/>Du point de vue pratique, ou du point de vue du manager redevable de la meilleure gestion des capitaux investis, la réponse est peut être différente.\
</li>\
</ol>\
<p>La vision de l'entreprise développée par les nouvelles générations, dites y, semble peu basée sur l'implication durable dans un projet d'entreprise mais plus sur des principes d'indépendance, d'employabilité, de rémunération directe.</p>\
<p>L'entreprise, oh surprise, n'est plus une magnanerie ou chaleur et nourriture garantissent la production du ver à soie. Hélas, les salariés risquent d'être de moins en moins des vers à soie, ce qui est en un sens dommage, et entraîne deux effets :</p>\
<ul><li> L'employeur n'a plus de raison, autre que de morale personnelle, de se montrer fidèle envers et contre tout : à peine la reprise venue, ses collaborateurs partiront quand même pour peu que l'herbe soit momentanément plus verte ailleurs. En ce sens, la comparaison avec le ver à soie reste pertinente, pour peu que l'on envisage sa mobilité !</li>\
<li> Du coup, l'employeur responsable devient celui qui ne s'encombre pas d'états d'âmes jamais récompensés, mais celui qui sait obtenir le meilleur équilibre de confort professionnel, i.e. répondre au mieux aux aspirations de reconnaissance, d'indépendance, de développement personnel et professionnel de ses collaborateurs.</li>\
</ul>\
<p>Plus que jamais la coordination entre la stratégie RH globale et sa concrétisation sur le terrain, son déploiement par les managers de proximité, est donc un enjeu pour garantir une implication durable des salariés dans l'entreprise et avec l'entreprise. </p>
<p style='text-align:right; font-weight : bold; margin: 10px;'>Léonard Briot de La Crochais</p>"


Blog.create! :status => "published", :published_at => "2009-07-09 13:54:01",
:permalink => "test", :title => "évaluation", :excerpt => "l'entretien d'évolution",
:text => "publié dans FocusRH."

Blog.create! :status => "published", :published_at => "2009-10-08 10:42:12", :permalink => "laureat-du-concours-creacc-2009", :title => "Lauréat du concours Cré'Acc 2009, 11ème Tremplin Entreprises",   :excerpt => "Qameha, lauréat du concours Cré'Acc 2009 organisé par l'Ordre des Experts Comptables et la Chambre de Commerce et d'Industrie de Paris",  :text => "<p>Après avoir été Lauréat du concours Cré'Acc 2009 organisé par l'Ordre des Experts Comptables et la Chambre de Commerce et d'Industrie de Paris, Qameha va maintenant participer au 11ème Tremplin Entreprises (<a href=\"http://www.tremplinentreprises.com\">www.tremplinentreprises.com</a>) coorganisé par le Sénat et l'ESSEC</p>"

Blog.create! :status => "published", :published_at => "2009-12-08 11:28:25", :permalink => "on-parle-de-nous", :title => "On parle de nous", :excerpt => "Le recrutement est un vrai défi pour les entreprises. Il ne suffit plus aux sociétés d'être concurrentielles et attractives pour que les meilleurs profils les rejoignent.", :text => "<h1>Un nouvel acteur du e-recrutement : Qameha</h1> <p>Le recrutement est un vrai défi pour les entreprises. Il ne suffit plus aux sociétés d'être concurrentielles et attractives pour que les meilleurs profils les rejoignent. Qameha est une application internet de gestion des recrutements, de la mobilité interne et des évaluations conçue et réalisée par des opérationnels des Ressources Humaines. Son but ? Simplifier et structurer le processus et conduire les cadres à s'impliquer eux-mêmes dans le recrutement de leurs équipes.</p> <p>My RH Line a rencontré Léonard Briot de la Crochais, Directeur de la Stratégie et des Partenariats de Qameha.</p>  <p>Retrouvez <a href=\"http://www.myrhline.fr/actualite-rh/un-nouvel-acteur-du-e-recrutement-qameha.html\">l'article complet</a> publié sur myrhline.com le 8 décembre 2009</p>"

Blog.create! :status => "draft", :published_at => "2009-10-08 11:10:39",
  :permalink => "colloque-national-innovation-emploi",
  :title => "Colloque national « l'innovation pour l'emploi » organisé par Yvon Gattaz",
:excerpt => "QAMEHA, spécialiste de la Gestion de la Valeur Humaine dans l'entreprise, intervient lors de la table ronde du colloque national <em> l'innovation pour l'emploi des jeunes </em>, organisé par l'association jeunesse et entreprise créée et présidée par Yvon Gattaz.",
:text =>
"<p>QAMEHA, spécialiste de la Gestion de la Valeur Humaine dans l'entreprise, intervient lors de la table ronde du colloque national <em> l'innovation pour l'emploi des jeunes </em>, organisé par l'association jeunesse et entreprise créée et présidée par Yvon Gattaz.</p> <p>Qameha a développé une application web (SaaS) pour les PME et Entreprises de Taille Intermédiaires (ETI) souhaitant améliorer significativement la gestion des compétences et de la valeur humaine dans l'entreprise. Ce logiciel comprend une suite de trois modules : recrutement,    évaluation    des    collaborateurs    et    mobilité    interne , destinés à acquérir des meilleurs éléments grâce à un processus de recrutement optimisé, motiver leurs collaborateurs et capitaliser sur les compétences internes grâce à un processus d'évaluations couplé un outil de mobilité interne.</p> <p>Grâce à Qameha les PME et ETI améliorent leur compétitivité à améliorant leur capacité d'acquisition et de fidélisation des meilleurs collaborateurs. Qameha limite à un groupe de clients partenaires l'utilisation de sa version beta jusqu'en janvier 2010. </p> <p>Le colloque national 2009 de l'AJE est ouvert par Monsieur Luc Chatel, Ministre de l'éducation national et clos par Madame Christine Lagarde, Ministre de l'économie et des Finances. Interviendront également, Messieurs Axel Kahn, Président de l'Université Paris- Descartes, Pascal    Morand, Directeur Général ESCP-Europe, Olivier Barberot, Directeur exécutif en charge des RH du groupe Orange, Jacques Servier, Président- Fondateur des Laboratoires Servier,Martin Hirsch, Haut Commissaire à la Jeunesse <br />Contacts Presse Léonard Briot de La Crochais Tel : 0173042773 leonard.briot@qameha.com</p>"

Blog.create! :status => "published", :published_at => "2009-10-08 11:10:39",:permalink => "colloque-national-innovation-emploi",  :title => "Colloque national « l'innovation pour l'emploi » organisé par Yvon Gattaz",:excerpt => "rien",:text => "rien"



#
#
#Blog.create! :status => "published", :published_at => "2010-10-22 08:04:38", :permalink => "qameha-recrute-2-developpeurs-ruby-on-rails", :title => "Qameha recrute 2 développeurs Ruby on Rails", :excerpt => "', 'Paris, le 2 septembre 2009  Qameha développe une application B2B en mode Saas dans le domaine des ressources humaines. Cette application est composée de plusieurs modules et le premier a déjà été adopté en béta test par des clients partenaires. Depuis début juillet, Qameha est hébergé au sein de l'incubateur de Télécom Paris Tech.  Nous recherchons deux développeurs Ruby on Rails junior ou expérimenté(e)  .  CDI Rémunération selon expérience.  Poste : Au sein d'une équipe de trois associés fondateurs, vous êtes complètement associé(e) au développement de l'entreprise. Vous reportez à l'associé en charge des IT (<a href="http://twitter.com/alexip">@alexip</a>) et prenez en charge le développement de modules fonctionnels, de l'écriture du code aux tests. Le développement est Agile. Nous mettrons en oeuvre des méthodes de développement <strong>Scrum et TDD</strong>.  Vous évoluez au rythme de la société soit en management (croissance de l'équipe IT), soit vers des axes de recherches (partenariats laboratoires), soit de web marketing.  Environnement technique - Ruby on Rails - Cucumber, Webrat - git, capistrano - mod_rails, ubuntu - mysql  Qualité du code / maintenance serveur / design d'interface seront 3 axes supplémentaires discriminant.  <strong>Anglais excellent impératif </strong>Lieu : Paris  Si vous êtes intéressé(e), contactez nous à <a href="mailto:qameha@qameha.com">qameha@qameha.com</a> en joignant votre cv,  Sinon n'hésitez pas à diffuser cette annonce.');
#
#
#'2009-07-04 19:01:19', 'mobilite-et-recrutement', 'Mobilité et recrutement !', ', 'Qameha teste avant ses clients son produit, un peu, et les réalités des PMEs, beaucoup :  - nous déménageons ! Merci à l'incubateur Télécom ParisTech Entrepreneurs de nous faire confiance et nous accueillir. On ne va pas très loin tout seul, et l'incubateur nous permet de partager un espace, des idées, des solutions, des cv, parce que ...  - nous recrutons : et recherchons des geeks ruby on rails à partir de la rentrée.  - Qameha met la GPEC (gestion prévisionnelle de l'emploi et des compétences) à la portée des PMEs, et la teste ! Cedric m'a appris à brancher mon ordinateur, Alexis se remet à l'anglais en prévision de notre croissance exponentielle, et nous savons maintenant tous faire fonctionner la machine à café.');
#'2009-07-09 13:54:01', 'donner-de-la-valeur-aux-entretiens-devaluation', 'Donner de la valeur aux entretiens d'évaluation', ', '« <em>Par exemple, l'entretien d'évolution est idéal pour la mobilité. Mais les données sont difficiles à exploiter sans outil informatisé</em>. » Francis Bergeron, DRH chez SGS.  « <em class="spip">La mobilité mérite d'être processée</em>. » Nicole Prud'homme, Directrice du département Talent Management du cabinet Hudson.  Retrouvez tout l'article "<a href="http://www.focusrh.com/article.php3?id_article=3763">Les DRH misent sur la mobilité interne</a>", publié dans FocusRH.');
#'2009-10-27 16:38:51', 'le-collaborateur-acteur-de-son-evolution-professionnelle', 'Le collaborateur, acteur de son évolution professionnelle', ', '"<em>Afin de rendre le collaborateur acteur de son évolution professionnelle, nous avons voulu que le logiciel de GPEC que nous avons déployé soit accessible non seulement au département RH et aux managers mais également aux collaborateurs. Ainsi le collaborateur a accès à ses propres informations (fonctions, entretien annuel...), le manager aux siennes et à celles de ses collaborateurs et ainsi de suite</em>." <span class="spip">Pierre-Marie Argouarc'h, DRH de la Française des Jeux.</span>  <span class="spip">Retrouver tout l'article <span style="background-color: #ffffff;">"<strong> <a href="http://www.focusrh.com/article.php3?id_article=4048">La mise en place de la GPEC doit être rapide</a></strong>", publié dans FocusRH le 22/10/09.</span></span>');
#'2009-11-10 13:26:06', 'lentretien-devaluation-une-etape-cruciale-en-periode-de-crise', 'L'entretien d'évaluation : une étape cruciale en période de crise', ', 'L'entretien d'évaluation est bien souvent vécu comme un challenge - de surcroît en la période actuelle. Ce point d'étape est le moment idéal pour dresser un bilan sur le travail effectué, parler des satisfactions, des attentes – dans la mesure du raisonnable – et pour fixer les objectifs pour la nouvelle année.  Retrouver tout l'article  <strong>"<a href="http://www.jobeticrh.net/L-entretien-d-evaluation-une-etape-cruciale-en-periode-de-crise_a256.html" target="_blank">L'entretien d'évaluation : une étape cruciale en période de crise</a>" publié sur Jobetic.Rh</strong>');
#'2009-11-10 13:32:21', 'conserver-ses-talents-en-periode-de-crise', 'Conserver ses talents en période de crise', ', 'Préserver vos collaborateurs talentueux est essentiel pour passer la crise et être prêt lors de la reprise économique.  Retrouver l'ensemble de l'article "<a href="http://www.journaldunet.com/management/ressources-humaines/conseil/conserver-les-talents-dans-son-equipe/conserver-ses-talents-en-periode-de-crise.shtml" target="_blank">Conserver ses talents en période de crise</a>" publié sur Le Journal du Net');
#'2009-12-09 15:09:01', 'de-limportance-des-comptes-rendus-dentretien-devaluation', 'De l'importance des comptes rendus d'entretien d'évaluation', ', 'Avec la fin de l'année qui approche, les entretiens annuels d'évaluation s'organisent. Certains peuvent être tentés d'en faire un simple rendez-vous formel. Pourtant la jurisprudence vient encore de rappeler que cette entrevue ne doit pas être prise à la légère, ni par l'employeur ni par le salarié.  Retrouver <a href="http://www.lentreprise.com/3/1/4/article.asp?ida=22027">l'article complet</a> publié le 7 décembre 2009 sur www.lentreprise.com');
'2010-01-06 12:10:16', '
recherchons-ruby-on-rails-jedi-master', 'Recherchons Ruby on Rails Jedi Master', ', '
Qameha Meha, Railers et Rubyists !


Nous cherchons un développeur Ruby + Rails de 2 - 5 ans d'experience :
- qui soit ceinture noire en langages objets\n- qui ne puisse coder sans d'abord écrire les tests\n- qui vendrai son âme pour pouvoir pair programmer\n\nL'équipe IT est actuellement composée de 3 personnes et communique principalement en anglais.\n\nPoste basé à Paris, rémunération selon expérience, ...\nContact : ror.qameha@qameha.net\n@qameha / @alexip \n');

